### ISSUE TITLE
Blockhelper

### ISSUE THREAD

**Issue by signalwerk** [helpers/handlebars-helper-moment#12]
I would expect for `{{#moment format="MMMM YYYY"}}2026-04-04{{/moment}}` an output like `April 2026`. But I get `April 2016` (current date). If the blockhelper would work, I could do something like:

`{{#moment format="MMMM YYYY"}}{{myHelper year}}{{/moment}}`

What do you think?

**Comment by doowb** [comment]
You should use subexpressions:

```handlebars
{{myHelper (moment year format="MMMM YYYY")}}
```
or
```handlebars
{{moment (myHelper year) format="MMMM YYYY"}}
```
depending on what exactly `myHelper` is doing/expecting.

**Comment by signalwerk** [comment]
Oh! I didn't know about subexpressions. Thank you!

**Comment by doowb** [comment]
np... [Here's a link](http://handlebarsjs.com/expressions.html#subexpressions) with more information. I should have put that in the previous comment.

**Comment by signalwerk** [comment]
:heart_eyes:
